# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: circle_test
          POSTGRES_HOST: 'localhost'
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: circle_test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "Pipfile.lock" }}
            - project-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv sync --dev
            python3 -m venv venv

      - save_cache:
          paths:
            - ./venv
          key: project-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
            pipenv run manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
