# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContainerPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contacts_contactcontainerpluginmodel', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'verbose_name': 'Contact Container',
                'verbose_name_plural': 'Contact Containers',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contacts_contactpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('icon', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('google-plus', 'Google Plus'), ('linkedin', 'LinkedIn'), ('skype', 'Skype'), ('email', 'Email'), ('github', 'Github'), ('phone', 'Phone')], default='facebook', max_length=254, verbose_name='Icon')),
                ('text', models.CharField(max_length=254, verbose_name='Text')),
                ('link', models.CharField(max_length=254, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
